require: 
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  Exclude:
    - db/**
    - db/migrate/**
    - bin/**
    - vendor/**/*

Bundler/GemComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Metrics/MethodLength:
  Max: 5

Layout/ClassStructure:
  Enabled: true
  Categories:
    association:
      - has_many
      - has_one
    attribute_macros:
      - attr_accessor
      - attr_reader
      - attr_writer
    macros:
      - validates
      - validate
    module_inclusion:
      - include
      - prepend
      - extend
  ExpectedOrder:
    - module_inclusion
    - constants
    - association
    - macros
    - public_attribute_macros
    - public_delegate
    - initializer
    - public_methods
    - public_class_methods
    - protected_attribute_macros
    - protected_delegate
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/LineLength:
  Max: 100

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/NumberConversion:
  Enabled: true

RSpec/AlignRightLetBrace:
  Enabled: false

RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/DescribeClass:
  Enabled: true

RSpec/NestedGroups:
  Enabled: true
  Max: 6

RSpec/MultipleExpectations:
  Enabled: true
  Max: 5

RSpec/ContextWording:
  Enabled: false

RSpec/SubjectStub:
  Enabled: true

Style/AndOr:
  Enabled: true
  EnforcedStyle: always
  Exclude:
    - app/controllers/**/*

Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    collect: map
    collect!: map!
    inject: reduce
    detect: find
    find_all: select

Style/ConstantVisibility:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false
      
Style/ImplicitRuntimeError:
  Enabled: true

Style/InlineComment:
  Enabled: true

Style/IpAddresses:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - describe
    - context
    - it
    - to
    - not_to
    - require
    - require_relative
    - shared_examples
    - shared_context
    - define
    - yield
    - expect_with
    - mock_with
  Exclude:
    - 'Gemfile'

Style/MethodCallWithoutArgsParentheses:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/MissingElse:
  Enabled: false

Style/MultilineMethodSignature:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/Send:
  Enabled: true

Style/SingleLineBlockParams:
  Enabled: true
  Methods:
    - reduce:
        - accumlator
        - element

Style/StringHashKeys:
  Enabled: true
